
<?php
$order = $this->getInfo()->getOrder();
$payment = $order->getPayment();
$method = $payment->getMethod();
$url_store =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);
$transaction_id = isset($payment->getAdditional_information()['transaction_id']) ? $payment->getAdditional_information()['transaction_id'] : null;
$total = $order->getGrandTotal();
$imageIcon = $url_store . 'media/mageshop/belluno/images/belluno.png';
if ($method == 'belluno_bankslip') : 
    $dataBankslip = $payment->getAdditional_information('bankslip');
    if($dataBankslip){
        $jsonDataBankslip = json_decode($dataBankslip, true);
        $digitableLine = $jsonDataBankslip['digitable_line'];
        $url =  $jsonDataBankslip['url'];
        $transaction_id = isset($jsonDataBankslip['id']) ? $jsonDataBankslip['id'] : null;
    }
?>
<div class="box-bankslip">
    <div class="digitable-line">
        <div class="banner" style="background-image: url('<?php echo $imageIcon?>');"></div>
        <h3><?= Mage::helper('core')->__("Boleto Bancario - Belluno") ?></h3>
        <h4><b>Linha digitável:</b> <?= $digitableLine ?></h4>
        <button style="background-color: #2a87f1;" onclick="window.open('<?= $url ?>');" class="button btn-proceed-checkout btn-checkout" title="Imprimir Boleto" type="button">Imprimir Boleto</button>
    </div>
</div>
<?php endif;?>

<?php if($transaction_id != null): ?>
<div class="header_force_update">
    <a href="javascript:void(0)" onclick="Belluno.update('<?=$url_store?>belluno/consult?<?=$method?>=<?=$transaction_id?>');">Força atualização do pedido</a>
</div>
<style>
    .header_force_update {
        display: block;
        margin-top: 10px;
    }
    .header_force_update a{
        padding: 5px;
        background:#f5854b;
        color:#FFF;
    }
    .digitable-line .banner {
        width: 100%;
        max-width: 245px;
        height: 60px;
        background-size: 243px;
        background-repeat: no-repeat;
    }
    .digitable-line h3 {
        color: #005aad;
        text-align: left;
        font-weight: 700;
        font-size: 17px;
        border-bottom: 1px solid;
        padding-left: 10px;
        width: auto;
    }

    .digitable-line h4 {
        background: #00b83b;
        text-align: left;
        color: #FFF;
        padding: 7px;
        width: auto;
        border-radius: 3px;
    }
</style>

<?php endif; ?>

<div style="clear:both; margin-bottom: 20px"></div>