
<?php

$order = $this->getInfo()->getOrder();
$payment = $order->getPayment();
$method = $payment->getMethod();
if($method !== 'belluno_creditcard'){
    return false;
}
$url_store =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);
$transaction_id = isset($payment->getAdditional_information()['transaction_id']) ? $payment->getAdditional_information()['transaction_id'] : null;
$total = $order->getGrandTotal();
$viewJson = $payment->getAdditional_information('view'); 
$viewData = json_decode($viewJson, true);
?>
<style>
    .col {
        display: block;
        width: 100%;
        margin: 1px;
    }
    .key{
        display: inline-block;
    }
    .value{
        display: inline-block;
    }
</style>
<br>
<div class="box-creditcard">
    <h2><?= "Informações do pagamento:" ?></h2>
    <?php
    $num = 0;
    foreach ($viewData as $value) :
        $num++;
        $rest = $num % 2; ?>
        <?php if ($rest == 0) : ?>
            <b class="key"><?= $value ?></b>
            </div>
        <?php else : ?>
            <div class="col">
            <p class="value"><?= $value ?></p>
        <?php endif; ?>
        
    <?php endforeach; ?>
</div>


<?php if($transaction_id != null): ?>
<div class="header_force_update">
    <a href="javascript:void(0)" onclick="Belluno.update('<?=$url_store?>belluno/consult?<?=$method?>=<?=$transaction_id?>');">Força atualização do pedido</a>
</div>
<style>
    .header_force_update {
        display: block;
        margin-top: 10px;
    }
    .header_force_update a{
        padding: 5px;
        background:#f5854b;
        color:#FFF;
    }
</style>

<?php endif; ?>

<div style="clear:both; margin-bottom: 20px"></div>