
<?php
$order = $this->getInfo()->getOrder();
$payment = $order->getPayment();
$method = $payment->getMethod();
$url_store =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);
$transaction_id = $payment->getAdditionalInformation('transaction_id');
$total = $order->getGrandTotal();
$link_payment = $payment->getAdditionalInformation('link_payment'); 
$link_payment = json_decode($link_payment, true);
$link = $link_payment['link'];
$link = str_replace('\\', '', $link); // Remove as barras invertidas
?>
<div class="box-bankslip">
    <div class="digitable-line">
        <h3><?= Mage::helper('core')->__("Link de Pagamento - Belluno") ?></h3>
        <button style="background-color: #2a87f1;" onclick="window.open('<?= $link ?>');" class="button btn-proceed-checkout btn-checkout" title="Imprimir Boleto" type="button">Link de pagamento</button>
    </div>
</div>
<div style="clear:both; margin-bottom: 20px"></div>

<?php if($transaction_id != null): ?>
<div class="header_force_update">
    <a href="javascript:void(0)" onclick="Belluno.update('<?=$url_store?>belluno/consult?<?=$method?>=<?=$transaction_id?>');">Força atualização do pedido</a>
</div>
<style>
    .header_force_update {
        display: block;
        margin-top: 10px;
    }
    .header_force_update a{
        padding: 5px;
        background:#f5854b;
        color:#FFF;
    }
</style>

<?php endif; ?>

<div style="clear:both; margin-bottom: 20px"></div>