
<?php

$order = $this->getInfo()->getOrder();
$payment = $order->getPayment();
$method = $payment->getMethod();
if($method !== 'belluno_pix'){
    return false;
}
$url_store =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);
$transaction_id = isset($payment->getAdditional_information()['transaction_id']) ? $payment->getAdditional_information()['transaction_id'] : null;
$total = $order->getGrandTotal();
$pix = json_decode($payment->getAdditional_information()['pix'], true); 
$pix_expires_at = isset($pix['pix']['expires_at']) ? Mage::getModel('core/date')->timestamp($pix['pix']['expires_at']) : 0; 
$currentTimestamp = Mage::getModel('core/date')->timestamp(time());
$transaction_id = isset($pix['id']) ? $pix['id'] : null;
$status = $payment->getAdditionalInformation("status");
if(isset($pix) && $status == 'Open' && !$order->hasInvoices()):
$code = base64_decode($pix['pix']['base64_text']); 
?>
<style>
    .payment-pix.order-detalhes-pix-info {
        width: 100%;
        margin: 0;
        display: table;
        background-color: #ffffff0a;
        border: solid 1px #ffffff0a;
        padding: 0px;
        box-sizing: border-box;
    }
    .payment-pix .qrcode-info {
        width: auto;
        display: inline-block;
        float: none;
        margin: 25px 10px;
    }
    .payment-pix .qrcode-info img {
        width: 85%;
        max-width: 150px;
        margin: auto;
        display: table;
        padding: 10px;
        box-sizing: border-box;
        box-shadow: 0 0 10px rgb(0 0 0 / 12%);
        border-radius: 5px;

    }
    .payment-pix .titulo-pagar-pix {
        font-size: 22px;
        color: #000;
        text-align: center;
        margin-top: 15px;
        line-height: 1.2em;
        text-transform: none;
        font-weight: 600;
    }
    .payment-pix .copyCode-info {
        width: 60%;
        display: inline-block;
        margin: 30px auto;
    }
    .payment-pix .copyCode-info input{
        width: calc(100% - 140px);
        height: 45px;
        line-height: 45px;
        font-size: 12px;
        border: solid 1px #666;
        border-radius: 3px;
        padding: 0 20px;
        box-sizing: border-box;
    }
    .payment-pix .copyCode-info input:focus{
        background-color: #f8f8f8;
        outline:none;
        border: solid 1px #111;
    }
    .payment-pix .info-expire {
        font-size: 11px;
        color: #999;
        margin-top: 25px;
        text-align: center;
    }
    .payment-pix .copyCode-info .fieldcopycode {
        max-width: 130px;
        width: 100%;
        height: 45px;
        line-height: 45px;
        font-size: 22px;
        padding: 0 5px;
        float: right;
        background: #000;
        color: #fff;
        border-radius: 3px;
        cursor: pointer;
        text-align: center;
    }
    .payment-pix .copyCode-info .fieldcopycode:hover {
        background: #111;
    }
    
    @media only screen and (max-width: 767px) {
        .payment-pix .copyCode-info input{
            width: calc(100% - 00px);
        }
        .payment-pix .titulo-pagar-pix {
            font-size: 18px;
        }
        .payment-pix .copyCode-info {
            width: 100%;
        }
        .payment-pix .copyCode-info .fieldcopycode {
            max-width: 100%;
            margin-top: 8px;
            margin-bottom: 15px;
        }
        .payment-pix .qrcode-info img {
            width: 100%;
        }
    }
    .payment-pix .total-info {
        margin: auto;
        width: 40%;
        display: inline-block;
        max-width: 267px;
        text-align: center;
        padding: 5px;
        margin-top: 5px;
        margin-bottom: 5px;
        border: 1px solid;
        border-color: #0d9547;
        border-radius: 3px;
        display: inline-block;
    }

    .payment-pix .total-info .price{
        color:#0d9547;
        font-weight: 500;
        font-size: 17px;
    }
    .payment-pix .total-info span {
        font-size: 15px;
        font-weight: 600;
        color: #0d9547;
        margin-right: 2px;
    }
</style>
    <div class="payment-pix order-detalhes-pix-info">
    <div class="titulo-pagar-pix">Fazer Pagamento Pix/QR Code:</div>
    <div class="qrcode-info">
        <img src="data:image/png;base64,<?=$pix['pix']['base64_image']?>">
    </div>
    <div class="copyCode-info">
        <input type="text" value="<?=$code;?>" id="pixTextBelluno">
        <div class="fieldcopycode" onclick="copiarTextoPix(this)">Copiar</div>
        <p class="info-expire">O QR Code expira em: <?php echo date('d/m/Y H:i:s', $pix_expires_at); ?></p>
    </div>

</div>
<?php else: ?>
    <div> <b><?= Mage::helper('core')->__("Belluno - Pix") ?></b></div>
<?php endif; ?>


<?php if($transaction_id != null): ?>
<div class="header_force_update">
    <a href="javascript:void(0)" onclick="Belluno.update('<?=$url_store?>belluno/consult?<?=$method?>=<?=$transaction_id?>');">Força atualização do pedido</a>
</div>
<style>
    .header_force_update {
        display: block;
        margin-top: 10px;
    }
    .header_force_update a{
        padding: 5px;
        background:#f5854b;
        color:#FFF;
    }
</style>

<?php endif; ?>

<div style="clear:both; margin-bottom: 20px"></div>