<?php 
$baseUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);
$imageIcon = $baseUrl . 'media/mageshop/belluno/images/icon-cartao_de_credito.png';
$order = $this->getInfo()->getOrder();
$title = $this->getMethod()->getTitle();
?>
<style>
    .pixpayment_belluno {
        width: auto;
        max-width: 200px;
        display: flex;
        align-items: center;
    }
    .pixpayment_belluno img {
        width: 35px;
        margin-right: 10px;
    }
    .pixpayment_belluno p {margin-left: 10px;}
</style>
<div class="pixpayment_belluno">
    <img src="<?php echo $imageIcon?>" alt="<?php echo $title; ?>" width="120px">
    <p><?php echo $title; ?></p>
</div>
